travis:
  secure:
    BINSTAR_TOKEN: ZlKdzQTVesyart/4iiFIfcWILKqorPN7eO7LP8UyytPuKQRvytXIsysRiGHGi6nQBimtDt/Q61eDKYa55VLrIQGW2wTqGTPuxALkHZ6OIkrsmD3SxqkU7evVWdUL7qJ5HulGNg4x808+pdIdPLBPKxHKuBSjqHht2QsTJDYeQDnxUNCYU5jLZqtMUN/11GJ2IBaTFmoSDkLfB+Csax42hAT0YmBJoOBEoD7d8QuItZPuxsR5DTBcwhgqAww9rmjF3/ntezC+dEuhfSPoj3+qYuS8+JYk4Tp9SJAhqabQMkH5GXQ1KdlILIRp9zRto8enOF0ad7wJtQ5VN62HvDed5mXcnDN/C4er5TnFTPqScJemiErtRdVEjjDJn09gCz7Jp/A5fVSj30zueaR72RlWqn5bZ5tYO16R18w+QhDnnwDhnh5xc9cUvfEEAO7QLBnGxNfiFnhICVCZA6tedNQiaSFFdcdINCyfxYNP0Z++Ipp/RVnLh09sWLY8A9+xwrpDJe3W1Da9phfrOnsUqlZA3qjiEuo/vdzZaMRCSpe0pgYJn3UwDamrnGPwYhgZPnbPJsnuZ3Xv0Q+zzjHmypDuj0pKRhu7wgpuJIiRqu8ATeOryYO4ci7Had2EgwJvki+zjmCYcxjXuzvL4swd0KyDLHLaqbmlMjTb6VQpMoYagts=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
