travis:
  secure:
    BINSTAR_TOKEN: J/Fp+5laYEc4OT1XuHC397o2uXcTiVzqZxNZQYahai3SQeo+1TG6NJi5jR7vWi6/+mpgiAnLrxj+/pIUqsd55baAEPwHCfSDoBEwkKbckT56I6BF2wkNaXdxZQenqOqLFrxtBCMIMApUlAZmKAtgSx47oKWVoxrZrHPxevVUDgcs8JqF9Xwa59YDVitCAU0CA1g6eM7x9xtjk4HKmT2LLYLFUmRPNi2OVAGKYmsglEugFw1vQBPvvs7vIhE+WxcAIyhJbnQaw70Hb9PVdRsTOJYDi8GYHEr80nZeZUOmn1zatHjrXuiOqDZMDBCF8RJgPb70MKRZrL52RMbr0Ekmu1uENiwpmWWJPu3RVuj5mBuaH3+Y+9PEzZ7q8dDGRwdoxXE8g698KNKR0tUeAcA0hjOSD2PSlvVFlv5jlzj/ce5YlV6CXO2sJqVjli0k7H9qeykdSGVyi1kMZ7Zj2qpFpSBVm5CzGXB+IVPq6zKoBF6W6dgef9HkfFMO5S1H1T3i9rC1jhlRGZBPWGlojSe5vhtOWnQkYshRF2wR+/P5deX2JVhwucMH33gfSCrJT359f8aaVZENiajdzfYT4a7+pcCKy1i+GjdwaworuL2njk9sikNxg6EQq3yXLEiwDE1JofpDJPrrpsIwzetEgPL+YtPEEK5eJVl6GaMyC9k4r74=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
